### ISSUE TITLE
Want to add a dice game in JS

### ISSUE THREAD

**Issue by Shreyan-12345** [SandeepKrSuman/project-gallery#73]
pls assign me this task

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name. Make sure that the gif only shows the project rather than capturing whole window/tabs.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
